apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: mcd
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: hello
          image: ghcr.io/adriensieg/mcd-hello:fc9840d74938644fc46a5d6ea18038d4949b7bfd
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 15
            periodSeconds: 30
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits: { cpu: "500m", memory: "256Mi" }
